name: Build and deploy Python app to Azure Web App - retailappcloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # … your checkout, setup-python, pip install, zip, upload-artifact …

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: retailappcloud
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B96CD6E748B0435B8CE263129B8EF695 }}
          package: '.'            # <— add this line
